version: "3.8"
services:
  tornado:
    build: .
    container_name: iti_challenge01_master
    command: ["DevOps-Challenge-Demo-Code/hello.py"]
    environment:
      - ENVIRONMENT=dev
      - HOST=localhost
      - PORT=6379
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    ports:
      - "4222:4222"
  
  redis:
    image: redis:alpine
    container_name: redis_iti_challenge01_master
    expose:
      - 6379
    