 
version: "3.3"
services:
  tornado:
    build: .
    container_name: python_iti_challenge_master
    command: ['hello.py']
    
    environment: 
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ENVIRONMENT=Production 
      - HOST=localhost
      - PORT=4222
    depends_on: 
      - redis
    ports: 
      - "4222:4222"

  redis:
    image: redis:alpine
    container_name: redis_iti_challenge_master
    expose:
      - 6379
